bootutil: Fix some misspelling variables
mcu-tools/mcuboot pull request #1035
Opened 2021-06-23 13:38 UTC by FarK

There ir a couple of misspelled variables (slot -> active_slot).

fix #1028

Signed-off-by: Carlos Falgueras García <carlos.falgueras@wslw.es>

2021-06-23 18:16 UTC, d3zd3z requested changes
The change itself is fine. I suggest fixing the "ir" to perhaps "are" in the commit text, though :-)

2021-06-24 06:24 UTC, FarK commented
Of course, thank you for the feedback :)

2021-06-25 10:47 UTC, nvlsianpu approved these changes

2021-06-25 17:34 UTC, d3zd3z approved these changes

2021-06-25 17:34 UTC, merged