bootutil: Do not include mcuboot_logging.h when logging is disabled
mcu-tools/mcuboot pull request #1036
Opened 2021-06-23 13:41 UTC by FarK

This frees the user from the need of create an empty "mcuboot_logging.h"
when the logging is disabled.

Signed-off-by: Carlos Falgueras García <carlos.falgueras@wslw.es>

2021-06-25 17:41 UTC, d3zd3z approved these changes
LGTM

2021-07-20 11:36 UTC, FarK commented
@nvlsianpu could you review this please? Thanks.

2021-07-20 12:13 UTC, nvlsianpu commented
sure

2021-07-20 12:27 UTC, nvlsianpu requested changes
I think include will miss macros:
MCUBOOT_LOG_MODULE_DECLARE()
MCUBOOT_LOG_MODULE_REGISTER()
if  if MCUBOOT_HAVE_LOGGING is not enaled.

2021-07-21 07:25 UTC, FarK commented
Aargg. Yes, of course. I've sent another patch that should fix this. I probably should have put both of them into the same PR, I didn't notice that there is a dependency between them.

This is the other PR I'm talking about: https://github.com/mcu-tools/mcuboot/pull/1045/commits/8245d23ec4b11fcb70b28d1b5854bd959b7bb148

Thank you!

2021-07-21 07:43 UTC, nvlsianpu commented
you maenad ^^ https://github.com/mcu-tools/mcuboot/pull/1045

2021-07-21 07:54 UTC, nvlsianpu commented
ok, so let's merge #1045 first

2021-07-21 07:56 UTC, nvlsianpu commented
Or maybe: Can you add this commit to it?

2021-07-21 08:02 UTC, FarK commented
> Or maybe: Can you add this commit to it?

Yes, of course.

2021-07-21 09:48 UTC, nvlsianpu commented
included in #1045

2021-07-21 09:48 UTC, closed without merging