Update path to devicetree python package lib files
mcu-tools/mcuboot pull request #1044
Opened 2021-06-30 10:34 UTC by endiancj

This PR updates the path to the devicetree python package lib files according to this Zephyr PR [zephyrproject-rtos#33746](https://github.com/zephyrproject-rtos/zephyr/pull/33746) which moved the devicetree lib files.

Old path: `ZEPHYR_BASE/scripts/dts/`
New path: `ZEPHYR_BASE/scripts/dts/python-devicetree/src/devicetree/`

This PR solves the issue [mcuboot#1043](https://github.com/mcu-tools/mcuboot/issues/1043) Without this fix mcuboot won't build with zephyr 2.6.0.

2021-07-06 18:09 UTC, d3zd3z approved these changes

2021-07-21 08:57 UTC, nvlsianpu commented
cc @mbolivar-nordic

2021-07-21 09:20 UTC, nvlsianpu approved these changes

2021-07-21 09:25 UTC, nvlsianpu commented
@endiancj Can you fix commit message

It should looks like:
``` Console
zephyr: update devicetree py package lib files include path in assembly

This PR updates the path to the devicetree python package lib files according to this Zephyr PR
zephyrproject-rtos#33746 which moved the devicetree lib files.

Old path: ZEPHYR_BASE/scripts/dts/
New path: ZEPHYR_BASE/scripts/dts/python-devicetree/src/devicetree/

Signed-off-by: Carl-Johan Landin <carl-johan.landin@endian.se>
```

2021-07-21 09:28 UTC, nvlsianpu requested changes
^^

2021-07-21 09:33 UTC, endiancj commented
@nvlsianpu no problem, I will fix the commit message. I’m on vacation atm but will most likely have time on Friday.

2021-07-21 14:51 UTC, mbolivar-nordic approved these changes
Code changes look fine

2021-07-21 22:22 UTC, d3zd3z commented
Please put the nice description that is in the github PR in the commit itself. It is fairly challenging to find a PR after a commit is made, but the commit text will be visible to anyone viewing the repo.

In addition, you'll need a signed off by line at the end of the commit text.

2021-07-24 20:58 UTC, endiancj commented
I just updated the commit message to your proposal @nvlsianpu, including the signed-off-by line. Thanks for the feedback :+1:

2021-07-26 08:18 UTC, nvlsianpu approved these changes

2021-07-26 08:19 UTC, merged