Prevent compilation of Espressif files on Mbed build
mcu-tools/mcuboot pull request #1096
Opened 2021-08-12 12:13 UTC by lambda-shuttle

The old mbed CLI 1 tool, currently used to compile the MCUboot port for Mbed™ OS, compiles all files unless otherwise specified in `.mbedignore`.   The espressif directory in the boot folder was added to the ignore file to prevent failed builds. 

@pan-

2021-08-12 12:35 UTC, pan- approved these changes

2021-08-12 21:39 UTC, d3zd3z approved these changes

2021-08-12 22:38 UTC, d3zd3z requested changes
As mentioned by the failing test, you'll need to add a Signed-off-by line to the commit text. It is a little difficult getting that to happen with commits made by github. Maybe we should change our checking script. If you (Sudarshan) would like one of the maintainers to rebase the commit so that isn't needed, let us know. But, you will need to add the SoB to this commit. If you want us to do it, just state permission in a comment and we can also add a SoB for you.

2021-08-13 08:56 UTC, lambda-shuttle commented
Thanks for the information! I'll keep this in mind when making pull requests in the future. Yes, I'm fine with the repository's maintainers adding a SoB line for me.

2021-08-13 15:35 UTC, d3zd3z commented
I also added the additional text from the PR to the commit.

2021-08-13 16:22 UTC, d3zd3z approved these changes

2021-08-13 16:22 UTC, merged