Add configuration parameter to enable internal MCUboot logging.
mcu-tools/mcuboot pull request #1141
Opened 2021-09-15 03:20 UTC by AGlass0fMilk

Prior to this commit, it was not possible for a user to enable `MCUBOOT_HAVE_LOGGING` through the existing Mbed-OS configuration parameters. This commit fixes this by adding an option: `mcuboot.enable-logging`. Now, logging that is performed by MCUboot's internal sources will be printed as well as logging that is part of the Mbed-OS port.

Signed-off-by: George Beckstien <george.beckstein@gmail.com>

2021-09-15 15:11 UTC, AGlass0fMilk commented
@LDong-Arm @boraozgen

2021-09-15 15:13 UTC, utzig commented
> Signed-off-by: George Beckstien [george.beckstein@gmail.com](mailto:george.beckstein@gmail.com)

Gerge, does your real surname and your email surname differ on purpose?

2021-09-17 22:27 UTC, d3zd3z requested changes
Change looks fine, please format the commit text to 75 columns.

2022-06-29 00:06 UTC, d3zd3z commented
This will need to be rebased, and the first line of the commit text should probably start with "mbed: " to make it clear to people reading the history that this is specific to Mbed-OS.

Is there still interest in getting this merged?

2022-07-13 02:39 UTC, closed without merging