boot: Avoid overflow if header size is too big and encryption is used
mcu-tools/mcuboot pull request #1192
Opened 2021-11-03 07:22 UTC by kvaellning

Fixes issue #1191.

This tries to prevent misconfiguration of the header size in the imgtool,
and also adds code which prevents the overflow if the (not encrypted) header
is skipped.

2021-11-05 17:43 UTC, d3zd3z requested changes

2021-11-05 17:43 UTC, d3zd3z commented on boot/bootutil/src/loader.c
> +                    /* check for overflow, return BOOT_EBADIMAGE */
`/* Check for overflow. */` is sufficient. Stating what the return does is redundant and just increases the likelihood that the code gets changed in the future and the comment missed.

2021-11-05 17:43 UTC, d3zd3z commented on scripts/imgtool/image.py
> +IMAGE_HEADER_SIZE_MAX = 0x400 # limited by buffer size in loader.c:boot_copy_region
It might also be helpful to put a comment in loader.c where the buffer is defined that it should match this declaration here.

2021-11-08 13:14 UTC, nvlsianpu commented
@kvaellning I opened alternative to your patch, see #1199

2021-11-09 17:51 UTC, d3zd3z requested changes
Updates look good. Can you please squash the commits, and repush (with -f)?

2021-11-10 06:40 UTC, kvaellning commented
@d3zd3z I am a little bit unsure here - as mentioned by @nvlsianpu, there is a better fix already provided. Anyway, I will just bundle it together, but if it's not requiered anymore then I would simply close the pull-request.

2021-11-15 12:51 UTC, kvaellning commented
Closed since fixed.

2021-11-15 12:51 UTC, closed without merging