boot: zephyr: stm32: watchdog support
mcu-tools/mcuboot pull request #1207
Opened 2021-11-12 15:25 UTC by heinwessels

**Implements:**
- Support for the STM32 Independent watchdog.
- Feeding of watchdog during serial recovery mode.

**Tested:**
- Tested with custom STM32L431KC board with and without watchdog enabled. Watchdog successfully kicks bootloader when in `FIH_PANIC`.
- Tested with serial communication. Watchdog is being fed and does not reset bootloader when in `boot_serial_start`, or while uploading new image.

2021-11-17 17:01 UTC, d3zd3z requested changes
Minor little fixup needed.

2021-11-17 17:01 UTC, d3zd3z commented on boot/zephyr/include/mcuboot_config/mcuboot_config.h
> +#endif
There is a spurious space at the end of this line.

2021-11-18 22:03 UTC, d3zd3z approved these changes

2021-11-19 07:44 UTC, heinwessels commented
The CI failed because of an incorrectly formatted commit message. I fixed that, but need approval for it to build again. :)

2021-11-19 13:09 UTC, nvlsianpu approved these changes

2021-11-20 18:58 UTC, utzig approved these changes
LGTM

2021-11-20 18:58 UTC, merged