Sw version based downgrade prevention
mcu-tools/mcuboot pull request #1239
Opened 2021-12-13 14:52 UTC by mateo-ligne-netatmo

Hello everyone, 

This PR follow a [previous issue](https://github.com/mcu-tools/mcuboot/issues/1211)  where I express my need of having a software version comparison before loading a new firmware through **Recovery uart** in a **Single application slot** configuration. 

The firmware update will be monitored by **MCUmgr**, and in order to stop the update from it, I defined a new error type that will stop update process. This MCUmgr feature is the [following open PR](https://github.com/apache/mynewt-newtmgr/pull/187)

I also added a commit allowing to use 2 UART peripheral at the same time one for Logs and the other for MCUmgr communication. 
 
It's my first MCUBoot upload so don't hesitate to make feedbacks or suggestions, I will take them into account !

2021-12-16 01:28 UTC, utzig requested changes
Please sign-off your commits.

2021-12-21 22:30 UTC, d3zd3z requested changes
Can you also write a bit more in the commit text. The summary lines are good, but the body (above the signed off by line) should have a bit of an explanation as to why a change is being made. (probably not needed for the typo fix).

2021-12-21 22:30 UTC, d3zd3z commented on boot/boot_serial/src/boot_serial.c
> +    {
Brace should be at the end of the line with the if.

2021-12-21 22:30 UTC, d3zd3z commented on boot/boot_serial/src/boot_serial.c
> +        {
likewise

2021-12-21 22:30 UTC, d3zd3z commented on boot/boot_serial/src/boot_serial.c
> +        {
here as well

2021-12-21 22:30 UTC, d3zd3z commented on boot/boot_serial/src/boot_serial.c
> +    {
and here

2021-12-21 22:32 UTC, d3zd3z commented on boot/boot_serial/src/boot_serial.c
> +#endif /*MCUBOOT_DOWNGRADE_PREVENTION*/
Also, sorry to nit, but please put spaces between the comment characters and the symbol. I notice there are a few others that have snuck in without the spaces, but the original ones do have the spaces.

2021-12-27 09:24 UTC, mateo-ligne-netatmo commented on boot/zephyr/serial_adapter.c
> +#if DT_SAME_NODE(DT_CHOSEN(zephyr_uart_mcumgr), DT_CHOSEN(zephyr_console))
Yes, but what about the case where we want to have UART console and DFU over UART on two separate UART device ? As far as I understood this check disallow this possibility, whereas my changes enable it if console UART and MCUmgr UART are 2 differents devices.

2022-01-11 17:20 UTC, d3zd3z approved these changes
For future reference, please format the text of the commit text to 75-ish columns. If there are no other changes, I can fix this up before this goes in, however.

2022-02-08 13:54 UTC, mateo-ligne-netatmo commented
Hello, I have rebased my PR with current MCUboot main especially following https://github.com/mcu-tools/mcuboot/pull/1255. It turns out that on a failed firmware update (for too low SW version for instance), stored binary won't be overwritten but it will be decrypted a second time which will break the applicative. To counter that, I've just had a return code check before decryption.

2022-02-09 23:32 UTC, d3zd3z commented
I believe @utzig concerns have been addressed.

2022-07-08 15:26 UTC, nvlsianpu commented on boot/zephyr/serial_adapter.c
> +#if DT_SAME_NODE(DT_CHOSEN(zephyr_uart_mcumgr), DT_CHOSEN(zephyr_console))
@de-nordic Can you take a look on this and the next line?

2023-01-19 01:58 UTC, closed without merging

2026-02-27 16:35 UTC, Szewcson commented
It was 3 years ago, and it still not merged. I just encountered that problem working with [ncs](https://github.com/nrfconnect/sdk-nrf)