single_loader: boot_serial: Add support for encrypted images
mcu-tools/mcuboot pull request #1255
Opened 2021-12-20 16:19 UTC by wcappelle

Adding support to allow encrypted images to be send & decrypted over the serial recovery methods in a single application context. This has been done by decryption in place, and is not power failsafe, but can always be redone when failed. Anyhow serial recovery isn't power failsafe, so don't think this is a bad thing. On a STM32L0@32MHz with 100kb of imagesize, this process takes about 2 minutes to complete (transfer included 9600baud)

Signed-off-by: Wouter Cappelle <wouter.cappelle@crodeon.com>

2022-01-10 19:57 UTC, d3zd3z requested changes
Other than some minor whitespace issues, this looks ok to me.

2022-01-10 19:57 UTC, d3zd3z commented on boot/boot_serial/src/boot_serial.c
> +                        * decryption by clearing the flag in the heder. If
The is a stray space at the end of this line.

2022-01-10 19:57 UTC, d3zd3z commented on boot/zephyr/CMakeLists.txt
> +foreach (filepath ${CONF_FILE})
Cmake convention never has spaces between the keyword and the argument.

2022-01-11 08:32 UTC, wcappelle commented
@d3zd3z , thanks for your review. I've updated the requested changes.

2022-01-11 21:53 UTC, d3zd3z approved these changes

2022-01-13 21:05 UTC, merged