zephyr: Use k_busy_wait if multithreading is not activated
mcu-tools/mcuboot pull request #1293
Opened 2022-01-26 12:28 UTC by kvaellning

If CONFIG_MULTITHREADING is not set, k_sleep is not defined by Zephyr.

Signed-off-by: Robert Schulze <robert.schulze@deveritec.com>

2022-02-07 22:47 UTC, d3zd3z approved these changes

2022-06-23 13:05 UTC, nvlsianpu requested changes
-1 boot_log_thread_func() is intended to be run in its own thread. See `zephyr_boot_log_start()`.

I see no point to make it compatible with the single thread mode

2022-06-28 09:18 UTC, kvaellning commented
@nvlsianpu Then maybe just activate multi-thread mode in the prj.conf per default and generating a better error message during compile time?

2022-07-01 13:44 UTC, nvlsianpu commented
> @nvlsianpu Then maybe just activate multi-thread mode in the prj.conf per default

CONFIG_MULTITHREADING=y is by default for all with excuse to some of configuration of the nRF devices.

> ... and generating a better error message during compile time?

Compilation will miss for instance k_thread_create() as well. Do you think that something like error on CONFIG_MULTITHREADING=n should be added?

2022-07-04 08:24 UTC, kvaellning commented
> Compilation will miss for instance k_thread_create() as well. Do you think that something like error on CONFIG_MULTITHREADING=n should be added?

That might be the best solution. I'll update the pull request in the next time.

2023-01-16 01:52 UTC, closed without merging