boot:zephyr: should clear mpu config
mcu-tools/mcuboot pull request #1442
Opened 2022-08-16 11:13 UTC by lenghonglin

Hello , everyone. 

I use mcuboot those day, i met a very strange things that if not call `z_arm_clear_arm_mpu_config`, it will hard fault.
![image](https://user-images.githubusercontent.com/4686802/184865118-94e31fc4-4eec-49fd-9cf2-e02128085ac0.png)

I config SRAM MPU in zephyr
![image](https://user-images.githubusercontent.com/4686802/184865823-2fa1ec96-f746-45aa-8185-1fbe05cdf78d.png)

So , we should `z_arm_clear_arm_mpu_config` if `CONFIG_CPU_HAS_ARM_MPU` = y . 

Signed-off-by: honglin leng <a909204013@gmail.com>

2022-08-16 11:15 UTC, lenghonglin commented
@nvlsianpu  could you please review this prm thanks

2022-08-20 05:53 UTC, lenghonglin commented
![image](https://user-images.githubusercontent.com/4686802/185731111-1b84f9a9-8566-4c5f-a2c6-c9d62f17d7ce.png)
twister bug with nrf52840 ?

2022-09-08 11:23 UTC, nvlsianpu requested changes
Hi,
I think you should rather enable CONFIG_MCUBOOT_CLEANUP_ARM_CORE option for your build instead of this patch.
Or explain more on reason for which you want always clear the MPU (zephyr-rtos application does this on its own).

Build issue you encountered was related to zephyr -rtos main branch API change

2022-09-09 02:42 UTC, lenghonglin commented
> Hi, I think you should rather enable CONFIG_MCUBOOT_CLEANUP_ARM_CORE option for your build instead of this patch. Or explain more on reason for which you want always clear the MPU (zephyr-rtos application does this on its own).
> 
> Build issue you encountered was related to zephyr -rtos main branch API change

i test frdm_k64 and my board. the same thing is both disable `CONFIG_MCUBOOT_CLEANUP_ARM_CORE `,  but frdm_k64 is work fine , my board cannot boot. enable `CONFIG_MCUBOOT_CLEANUP_ARM_CORE ` is not a good way. 

So i think the difference is about `sram`. my board config mpu with sram.

It is good to clear mpu config before reboot, this will solve some mpu config that cannot boot success. 

In other words, this mr maybe sovle some issue, but does not introduce new problems, right?

2022-09-12 12:03 UTC, nvlsianpu commented
@lenghonglin I don't understand the reason for which you are not using  `CONFIG_MCUBOOT_CLEANUP_ARM_CORE=y`

2022-09-15 01:59 UTC, lenghonglin commented
> @lenghonglin I don't understand the reason for which you are not using `CONFIG_MCUBOOT_CLEANUP_ARM_CORE=y`

This is a good question,  enable `CONFIG_MCUBOOT_CLEANUP_ARM_CORE` although can solve this issue, but this is not a really solution.

let me think about this issue.

both `frdm_k64` and `my_board ` is disable  `CONFIG_MCUBOOT_CLEANUP_ARM_CORE`, but only `frdm_k64` can reboot success. this is can explain that there is other reason make `my_board` cannot reboot.  

I found the difference is about `mpu config`, so the best solution is should clear mpu config if config `CONFIG_CPU_HAS_ARM_MPU `

2022-09-26 14:21 UTC, nvlsianpu commented
@lenghonglin As you mention before you are using the custom with peculiar SRM MPU configuration - you should enable CONFIG_MCUBOOT_CLEANUP_ARM_CORE for your board - This option allows to cleanup mpu and more.

Let me know if you can't do that (with explanation).

2023-04-10 01:39 UTC, closed without merging