zephyr: allow the serial recovery without any GPIO defined
mcu-tools/mcuboot pull request #1485
Opened 2022-09-29 12:13 UTC by nvlsianpu

Despite MCUBOOT support waiting on serial interface it always
requires GPIO pin which is a mistake.

Introduced intermediate CONFIG_MCUBOOT_SERIAL_USE_GPIO Kconfig
hidden option and used it for make code related to the pin-detection
excluded when CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y.

if someone will find out that usage of GPIO trigger and waiting on
DFU make any sens then CONFIG_MCUBOOT_SERIAL_USE_GPIO might be made
configurable. For now I don't see a sense in making that.

2022-10-04 09:40 UTC, nvlsianpu commented
cc @nordicjamie

2022-10-04 09:43 UTC, nvlsianpu commented
cc @nordicjm

2022-10-04 10:42 UTC, nordicjm reviewed
Typo in commit *make any sense

2022-10-04 10:42 UTC, nordicjm commented on boot/zephyr/Kconfig.serial_recovery
> +	default y if! BOOT_SERIAL_WAIT_FOR_DFU
Space before !

2022-10-04 22:24 UTC, d3zd3z reviewed
I'm happy with the change, with the space fixed.

2022-10-04 22:24 UTC, d3zd3z requested changes
The space really does need to be fixed.

2022-10-06 06:38 UTC, nordicjm reviewed
Typo in commit still:
`DFU make any sens then CONFIG_MCUBOOT_SERIAL_USE_GPIO might be made`
->
`DFU make any sense then CONFIG_MCUBOOT_SERIAL_USE_GPIO might be made`

2022-10-11 09:22 UTC, nvlsianpu commented
@d3zd3z Can you revisit?

2022-10-11 09:25 UTC, nordicjm approved these changes

2022-12-20 12:38 UTC, nvlsianpu commented
@d3zd3z Pleas revisit

2023-07-27 13:15 UTC, nordicjm commented
Closing as this is no longer needed, there is now a serial recovery entrance selection and GPIO can be disabled. Though this shows an issue with indication as that needs to select GPIO, will raise a new PR for that.

2023-07-27 13:15 UTC, closed without merging