Feature/1494 add formal req mgmt
mcu-tools/mcuboot pull request #1495
Opened 2022-10-26 22:38 UTC by gregshue

This PR introduces formal requirements management using Doorstop (https://github.com/doorstop-dev/doorstop), a LGPLv3 licensed open-source requirements management tool being considered by Zephyr Project.  Doorstop supports tracing between requirement documents kept within the same repository.  Each document is kept in a separate directory, with each document item kept in a separate file.  The files are named with a document-identifying prefix followed by a unique item number.  The files contain the controlled fields plus item metadata (e.g., links, approval state, normative, etc).  

NOTE: It appears no open-source requirements management tool is capable of meeting all of the needs faced by MCUBoot.  At least this tool enables capturing, managing, and formally tracing/reporting requirements within this project.

This PR sets up a preliminary requirements document tree and populates the first 3 documents (StRS, SyRS, SyAD) with an outline structure (headers) following examples for IEC 29148:2018 examples for StRS and SyRS and following the 4+1 Architectural View Model for SyAD.  Content will be left for other PRs.

Empty documents have also been set up for each of the following expected system elements:
- OS
- UI
- Logging
- NVM (Flash? Storage?)
- Console for recovery application

2022-11-18 10:54 UTC, nvlsianpu requested changes
[DNM] for now, change is controversial

2022-11-18 20:24 UTC, gregshue commented
What is the controversy?

2022-11-21 11:10 UTC, tejlmand requested changes
While i'm very sure that more formal requirement handling can be very beneficial, then could we please have a discussion regarding the current process and in which ways the current practice is limiting ourselves.

What are the problems the MCUboot project / management of the project is facing, and what are the tools available that can help us.

Before jumping to a solution, like doorstop, which involves adding and maintaining 207 new files, then I would like to know, what is not working, and why is it not working ?
And how / who will maintain those files ? 

The PR states:
> NOTE: It appears no open-source requirements management tool is capable of meeting all of the needs faced by MCUBoot. At least this tool enables capturing, managing, and formally tracing/reporting requirements within this project.

and what are those needs and what tools has been examined ?

> This PR introduces formal requirements management using Doorstop (https://github.com/doorstop-dev/doorstop), a LGPLv3 licensed open-source requirements management tool being considered by Zephyr Project.

Link please ?
All reference I have found regarding doorstop in Zephyr is a mentioning at the TSC at `2022-07-20` together with other options.
https://docs.google.com/document/d/1_sFM1BTLHrwRA9pbNoD7XPHE3OuqXT0P04AlAS2dvTk
> - Requirement Management - Anas [10min]
>    - Discussion that we need to have this cross team (security, safety, testing) 
>    - Options to track include doorstop, github, jira, etc. 

That seems far from being close to be selected as a preferred tool.

2022-11-21 20:53 UTC, gregshue commented
> I would like to know, what is not working, and why is it not working ?
And how / who will maintain those files ?

Certifiably secure executables need tracing of implementation back through design and requirements to stakeholder needs. This is essential to meet requirements like the following from ETSI EN 303645, v2.1.1:

> Provision 4-1 A justification shall be recorded for each recommendation in the present document that is considered to 
be not applicable for or not fulfilled by the consumer IoT device
> Provision 5.6-5 The manufacturer should only enable software services that are used or required for the intended use or 
operation of the device.
> Provision 5.6-6 Code should be minimized to the functionality necessary for the service/device to operate. 
> Provision 5.6-9 The manufacturer should follow secure development processes for software deployed on the device. 

MCUboot does not seem to formally manage requirements, so the current process is no longer "working" (or sufficient to meet end user needs constrained by new regulations).  Whether the requirements are managed in doorstop or not, they need to be managed and maintained by the MCUboot project. 

Properly managing requirements demands revision control at the individual requirement level, system-unique identifier, etc. The historic use of spreadsheets and word docs has proven insufficient time and again. This has given rise decades ago to commercial tools.  Most requirements management packages and built-in capabilities are geared toward development of a single software application rather than a system, and usually do not support variation management (needed).

> > requirements management tool being considered by Zephyr Project
> Link please ?

No link.  It is being discussed in the TSC and Security Working Group. That is why I said it is being _considered_.

> ... That seems far from being close to be selected as a preferred tool.
Doorstop does not have all the features needed for managing requirements for an IoT solution, but it seems to be the closest we have available as open source.  Eventually mcuboot should eventually adopt and transition to whatever system Zephyr Project will put into place. Meanwhile we ought to move forward with something.

"Preferred" is an interesting word. AFAICT, doorstop is the **least bad** among the freely available options I am aware of.  I have working experience with DOORS Classic, Jira, Azure DevOps (ADO), and Jama. I can tell you that Jira and ADO native solutions do not scale well to number of formal requirement management layers we face with ISO 12207-based standards.

No matter what tool we use, the project needs to collect, organize, maintain, and trace relationships between **requirement statements**. Some tools do this with a centralized database. Doorstop does it with one file per statement.  No matter how it is archived we still have the same set of **statements, metadata, and contextual information** to manage. Realistically, we should be able to convert to a different tool at any time. What we already know is we already need better identification and traceabilty than provided by spreadsheets and textual documents.

2022-11-22 19:41 UTC, gregshue commented
> Perhaps we need to start with something much less formal, perhaps even just a document

We can certainly do that.  There are a few practicalities we need to keep in mind:

1. To be unambiguous, any individual requirement may be very wordy.
2. Some types of requirements are more concisely captured in tables and/or annotated diagrams.1. To support discussion, we will need each requirement to have a unique identification.
3. To support consumption, we will need the requirements to be organized in a predictable, rational structure
4. To support capturing the requirements at the different layers of responsibility and decomposition, we will need a separate section for each layer.
6. Lower layer requirements/architectural decisions are there to fulfill higher layer requirements.  We need to track that relationship.

Expect we will end up with a few hundred items across the various layers. Do you really want to start with all these in a single document?

2022-11-23 01:39 UTC, gregshue commented
The feedback shows that MCUboot is not open to working with any formal requirements management tool at this time.  The content has been captured in Markdown format and submitted in PR #1526 and this PR is being closed.

2022-11-23 01:39 UTC, closed without merging