zephyr: Add unaligned stack buffer writing
mcu-tools/mcuboot pull request #1533
Opened 2022-11-30 15:46 UTC by nordicjm

Fixes a bug when writing to devices which have memory alignment requirements with data being using directly from a zcbor-response whereby the alignment of the buffer data does not meet the requirements of the flash driver.

Fixes #1532

2022-11-30 16:00 UTC, nordicjm commented
@de-nordic @nvlsianpu

2022-12-01 10:26 UTC, de-nordic requested changes

2022-12-01 11:53 UTC, nordicjm commented on boot/boot_serial/src/boot_serial.c
> +#if defined(__ZEPHYR__) && CONFIG_BOOT_SERIAL_UNALIGNED_BUFFER_SIZE > 0
Fixed

2022-12-01 11:55 UTC, de-nordic approved these changes

2022-12-05 09:38 UTC, nvlsianpu requested changes

2022-12-05 09:38 UTC, nvlsianpu commented on boot/boot_serial/src/boot_serial.c
> +                break;
```suggestion
              goto out;
```

2022-12-05 09:41 UTC, nvlsianpu commented on boot/boot_serial/src/boot_serial.c
> +                break;
maybe it is ok

2022-12-05 09:41 UTC, nordicjm commented on boot/boot_serial/src/boot_serial.c
> +                break;
Fixed

2022-12-05 09:48 UTC, nvlsianpu requested changes
I'm afraid that the patch doesn't take into account the  `rem_bytes` and its procedure.

2022-12-05 09:54 UTC, nordicjm commented
> I'm afraid that the patch doesn't take into account the rem_bytes and its procedure.

That part of the code is unchanged, rem_bytes is set before this code runs, so if it is set then it will run like usual after the main write loop

2022-12-07 08:52 UTC, nordicjm commented
@nvlsianpu any comments?

2023-01-03 11:17 UTC, nvlsianpu approved these changes

2023-01-03 11:18 UTC, merged