MCUBoot: Implement multi memory boot feature
mcu-tools/mcuboot pull request #1628
Opened 2023-02-23 11:27 UTC by DOAR-Infineon

Implement multi memory boot feature

In the current implementation, the ability to launch several applications using different memory modes has been added.
Use cases: multi core and ram app boot alongside with flash based applications

- MCUBOOT_MULTI_MEMORY_LOAD 
--- Feature: partial multi-image boot for RAM based applications 
--- Feature: partial multi-image boot for Flash applications

2023-03-02 11:40 UTC, tamasban requested changes
What is the purpose of this change, could you elaborate? I'm just guessing that the goal might is to enable a single MCUBoot image to be able to process images whether they are residing in RAM or flash.

2023-03-02 11:40 UTC, tamasban commented on boot/bootutil/include/bootutil/bootutil.h
> +fih_int context_boot_go_flash(struct boot_loader_state *state, struct boot_rsp *rsp);
`fih_int` was replaced by `fih_ret` in this change:
https://github.com/mcu-tools/mcuboot/commit/5047f032c93fd8957be6529f8f1ad7a3fe626057

2023-03-07 20:22 UTC, DOAR-Infineon commented
> What is the purpose of this change, could you elaborate? I'm just guessing that the goal might is to enable a single MCUBoot image to be able to process images whether they are residing in RAM or flash.

These changes were made to make MCUBoot able to work with flash and ram images independently.
The use case that we need to support, a multi image configuration:
* Application_1 boots from RAM
* Application_2 boots from FLASH
* Application_N boots from FLASH

2023-03-22 15:28 UTC, DOAR-Infineon commented
@d3zd3z @tamasban 
Please review

2023-07-11 09:51 UTC, closed without merging