ci: mynewt: Use newt for downloading dependencies
mcu-tools/mcuboot pull request #1706
Opened 2023-05-11 20:51 UTC by sjanc

This makes sure that Mynewt targets have all required dependencies downloaded.

2023-07-23 23:18 UTC, utzig commented on ci/mynewt_install.sh
> +    cp -r /tmp/mynewt/repos .
What's the problem of using `mv`?

2023-07-24 08:35 UTC, sjanc commented on ci/mynewt_install.sh
> +    cp -r /tmp/mynewt/repos .
no problem, I'll update it to use mv

2023-08-09 14:19 UTC, d3zd3z requested changes

2023-08-09 14:24 UTC, nordicjm commented
Rebase needed

2023-08-09 21:46 UTC, utzig commented
I tried updating this PR with the suggested changes but it is broken because `newt new` creates a project that requires Mynewt 1.11.0 release which is not available yet. The new release is being made these week afaik. I suggest using #1777 right now and come back to this PR after Mynewt is fully released.

2023-08-10 14:02 UTC, sjanc commented
This should work now (you were unlucky to hit in the middle of me tagging repos for release;-)

2023-08-14 08:31 UTC, sjanc commented
Hi,

Why #1777 was merged instead of this?

2024-02-26 01:28 UTC, closed without merging