doc: imgtool: update align description
mcu-tools/mcuboot pull request #1851
Opened 2023-11-06 14:02 UTC by butok

Update the --align option values.
Add its description.
Delete [required], as it is optional now.

2023-11-06 15:31 UTC, nordicjm approved these changes

2023-11-06 15:33 UTC, nordicjm requested changes
This is not what is displayed when running `imgtool sign -h`, what actually shows is:
```
  --max-align [8|16|32]           Maximum flash alignment. Set if flash
                                  alignment of the primary and secondary slot
                                  differ and any of them is larger than 8.
  --align [1|2|4|8|16|32]
  -v, --version TEXT              [required]
  -s, --security-counter TEXT     Specify the value of security counter. Use
```

Please fix `imgtool sign` help output so it shows this

2023-11-07 08:45 UTC, butok commented
> This is not what is displayed when running `imgtool sign -h`, what actually shows is:
> 
> ```
>   --max-align [8|16|32]           Maximum flash alignment. Set if flash
>                                   alignment of the primary and secondary slot
>                                   differ and any of them is larger than 8.
>   --align [1|2|4|8|16|32]
>   -v, --version TEXT              [required]
>   -s, --security-counter TEXT     Specify the value of security counter. Use
> ```
> 
> Please fix `imgtool sign` help output so it shows this

Fixed.

2023-11-07 08:46 UTC, nordicjm approved these changes

2023-11-07 10:22 UTC, merged