Add BOOT_SERIAL_WAIT_FOR_DFU_ALWAYS Zephyr Kconfig option.
mcu-tools/mcuboot pull request #1903
Opened 2024-02-22 21:02 UTC by mondalaci

This PR adds the `BOOT_SERIAL_WAIT_FOR_DFU_ALWAYS` Kconfig option. When set to `n`, under normal circumstances, the bootloader doesn't enter serial recovery mode, allowing the firmware to start up as quickly as possible. However, when physically resetting the device, the bootloader enters serial recovery mode, which comes in very handy when the firmware is broken.

This patch was actually created by Vidar Berg at https://devzone.nordicsemi.com/f/nordic-q-a/108213/mcuboot-should-only-timeout-after-hardware-reset/469112 who allowed me to submit it here as a PR.

2024-02-26 15:08 UTC, nordicjm commented on boot/zephyr/Kconfig.serial_recovery
> +	  enters serial recovery mode if the board was physically reset.
This comment doesn't really make sense, what does resetting have to do with staying in serial recovery mode?

2024-02-26 15:12 UTC, nordicjm requested changes
Comment does not really make sense, and there already is a mode of entering serial recovery when physical reset button is used `CONFIG_BOOT_SERIAL_PIN_RESET`

2024-03-09 18:59 UTC, mondalaci commented
Sorry, the Kconfig description is inaccurate. The following description is accurate:

> If y, MCUboot enters serial recovery for the duration of BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT upon physically resetting the board. Otherwise, MCUboot immediately executes the application.

The use case is that I want the board to boot up as quickly as possible under normal circumstances, but I also want to be able to manually trigger the bootloader even if the application firmware is broken.

It's also worth mentioning that my device is battery-powered without a dedicated on/off switch, but it has a RESET button, so the timeout allows restarting the application firmware in case of a dead loop without getting stuck in the bootloader.

CONFIG_BOOT_SERIAL_PIN_RESET doesn't fulfill the above use case because:
- It doesn't time out when hardware reset is used but gets stuck in serial recovery mode.
- It delays the execution of the application firmware when the board is powered under normal circumstances. (My device has an optional battery, and it can be powered via USB, too.)

2024-09-06 08:53 UTC, mondalaci commented
Please remove the stale label. This commit has merit, and I'm using this Kconfig option.

2025-02-12 10:38 UTC, nordicjm commented
> The use case is that I want the board to boot up as quickly as possible under normal circumstances, but I also want to be able to manually trigger the bootloader even if the application firmware is broken.

Then use `CONFIG_BOOT_SERIAL_NO_APPLICATION`

2025-02-12 11:05 UTC, mondalaci commented
Where can I find the documentation of `CONFIG_BOOT_SERIAL_NO_APPLICATION`?

It's unavailable in https://github.com/nrfconnect/sdk-nrf/blob/main/modules/mcuboot/boot/zephyr/Kconfig

2025-08-27 02:09 UTC, closed without merging

2026-01-30 02:29 UTC, jalius commented
Why was this closed? This is a useful feature when using `CONFIG_RETENTION_BOOT_MODE=y`. The current option set `CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y`
`CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT=30000` always waits for DFU regardless of the boot type. We'd like a way to wait on a retention boot but not on a regular boot.

2026-01-30 07:32 UTC, nordicjm commented
> Why was this closed? This is a useful feature when using `CONFIG_RETENTION_BOOT_MODE=y`. The current option set `CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=y` `CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT=30000` always waits for DFU regardless of the boot type. We'd like a way to wait on a retention boot but not on a regular boot.

Submitter was asked to make changes, they never did, PR got stale, it got automatically closed. Feel free to take over the submitter's work and fix as required above

2026-01-30 07:38 UTC, mondalaci commented
@nordicjm You haven't replied to https://github.com/mcu-tools/mcuboot/pull/1903#issuecomment-2653389316, hence I gave up.

@jalius Feel free to take this over.

2026-01-30 07:43 UTC, nordicjm commented
> Where can I find the documentation of `CONFIG_BOOT_SERIAL_NO_APPLICATION`?
> 
> It's unavailable in https://github.com/nrfconnect/sdk-nrf/blob/main/modules/mcuboot/boot/zephyr/Kconfig

What does that repo have to do with MCUboot at all? https://github.com/mcu-tools/mcuboot/blob/main/boot/zephyr/Kconfig.serial_recovery#L176