boot: main: avoid unused build warning
mcu-tools/mcuboot pull request #1990
Opened 2024-07-01 16:14 UTC by sylvioalves

In case ESP32 SoC is used, *start will get
build warning as it is not used.

2024-07-01 16:15 UTC, sylvioalves commented on boot/zephyr/main.c
> +    void *start = (void *)(SRAM_BASE_ADDRESS + rsp->br_hdr->ih_hdr_size);
The other approach would be using `UNUSED(start)` in ESP32 #ifdef section.

2024-07-01 16:15 UTC, sylvioalves commented
@nordicjm @almir-okato PTAL.

2024-07-02 10:00 UTC, almir-okato approved these changes
LGTM

2024-07-08 06:27 UTC, nordicjm requested changes

2024-07-08 06:27 UTC, nordicjm commented on boot/zephyr/main.c
> -    void *start;
variables should be declared at start of function so this needs to stay, you can #ifdef around it here

2024-08-12 16:05 UTC, sylvioalves commented
@nordicjm I swiped the call order instead of creating an additional #ifdef just because of a single variable. Let me know if it fits you.

2024-08-20 14:16 UTC, nordicjm reviewed
this is not fixed, functions are being called before variables have been defined

2024-08-20 14:34 UTC, sylvioalves commented
@nordicjm Ok, taking your suggestion and adding #ifdef around it.

2024-08-21 09:19 UTC, nordicjm approved these changes

2024-08-21 09:20 UTC, merged