boot: Replace boot_encrypt by boot_enc_encrypt and boot_enc_decrypt
mcu-tools/mcuboot pull request #2017
Opened 2024-07-24 14:00 UTC by de-nordic

To be able to implement encryption with API that requires different
calls for encryption and encryption, the boot_encrypt
needs to be replaced with encryption/decryption specific functions.

Depends on:
- [ ] https://github.com/mcu-tools/mcuboot/pull/2003
- [ ] https://github.com/mcu-tools/mcuboot/pull/2004
- [ ] https://github.com/mcu-tools/mcuboot/pull/2013

2024-07-25 15:16 UTC, nvlsianpu requested changes

2024-08-02 11:06 UTC, de-nordic commented on boot/boot_serial/src/boot_serial_encryption.c
> +            if (slot == 0) {
Replaced with comment that does not involve callers. Btw. the function that has 0 stuff to process should not call the function in the first place.

2024-08-02 11:06 UTC, de-nordic commented on boot/bootutil/src/encrypted.c
> +    struct enc_key_data *enc = &enc_state[slot];
Fixed

2024-08-02 11:07 UTC, de-nordic commented on boot/bootutil/src/encrypted.c
> +    struct enc_key_data *enc = &enc_state[slot];
Fixed

2024-08-06 17:17 UTC, nvlsianpu reviewed
another rebase needed

2024-09-10 09:34 UTC, nordicjm approved these changes

2024-09-27 14:58 UTC, nvlsianpu approved these changes

2024-10-02 14:54 UTC, merged