imgtool's compression ARM thumb filter
mcu-tools/mcuboot pull request #2084
Opened 2024-10-04 11:41 UTC by michalek-no

Adds ARM thumb fileter to imgtool's LZMA2 compression.

2024-10-07 08:33 UTC, nordicjm requested changes
Typo in commit message: filter
No flag updating that I can see

2024-10-07 09:44 UTC, nordicjm commented on scripts/imgtool/image.py
> +                compression_flags = IMAGE_F['COMPRESSED_ARM_THUMB']
this needs to add both flags

2024-10-07 12:21 UTC, nordicjm approved these changes

2024-10-11 13:33 UTC, nvlsianpu approved these changes

2024-10-11 14:17 UTC, merged