Boot: Add 'revert' support to direct-xip mode
mcu-tools/mcuboot pull request #784
Opened 2020-08-12 07:57 UTC by davidvincze

The 'revert' mechanism in direct-xip is similar to the one in swap mode.
It also requires the trailer magic to be added to the signed image. When a
reboot happens without the image being confirmed at runtime (without the
image_ok flag being set), the bootloader considers the image faulty and
will attempt to boot the previous image instead. The images can also be
made permanent (marked as confirmed in advance) just like in swap mode.

2020-08-24 09:49 UTC, hakonfam commented on boot/bootutil/src/loader.c
> +#ifdef MCUBOOT_DIRECT_XIP_REVERT
I agree with this, the outermost for-loop now almost stretches beyond my monitor :)

2020-08-24 10:36 UTC, hakonfam requested changes
Also I would update the commit message to state that the image is deleted if its reverted.

2020-08-24 10:36 UTC, hakonfam commented on boot/zephyr/include/mcuboot_config/mcuboot_config.h
> +#ifdef BOOT_DIRECT_XIP_REVERT
```suggestion
#ifdef CONFIG_BOOT_DIRECT_XIP_REVERT
```

2020-09-24 23:11 UTC, utzig commented
Please rebase

2020-10-02 18:38 UTC, davidvincze commented on boot/zephyr/Kconfig
> +	  bootloader considers the image faulty and will attempt to boot the
Done.

2020-10-02 18:38 UTC, davidvincze commented on boot/bootutil/src/loader.c
> +#ifdef MCUBOOT_DIRECT_XIP_REVERT
Done.

2020-10-02 18:39 UTC, davidvincze commented on boot/zephyr/include/mcuboot_config/mcuboot_config.h
> +#ifdef BOOT_DIRECT_XIP_REVERT
Fixed.

2020-10-07 06:02 UTC, hakonfam approved these changes

2020-10-22 21:09 UTC, utzig requested changes
Would not it be better to make this just part of the standard `DIRECT_XIP` instead of adding a new option?

2020-10-22 21:09 UTC, utzig commented on boot/bootutil/src/loader.c
> +            rc = boot_select_or_erase(slot_state, selected_slot);
...erase(`&slot_state`, ...)

2020-10-22 21:09 UTC, utzig commented on boot/bootutil/src/loader.c
> +    rc = flash_area_open(fa_id, fap);
`rc = flash_area_open(fa_id, &fap);`

2020-10-22 21:09 UTC, utzig commented on boot/bootutil/src/loader.c
> +    rc = boot_read_swap_state(fap, &state);
`rc = boot_read_swap_state(fap, state);`

2020-10-29 12:20 UTC, davidvincze commented on boot/bootutil/src/loader.c
> +            rc = boot_select_or_erase(slot_state, selected_slot);
Fixed. I have no idea what I was doing..

2020-10-29 12:21 UTC, davidvincze commented on boot/bootutil/src/loader.c
> +    rc = boot_read_swap_state(fap, &state);
Fixed.

2020-10-29 12:21 UTC, davidvincze commented on boot/bootutil/src/loader.c
> +    rc = flash_area_open(fa_id, fap);
Fixed.

2020-10-29 14:27 UTC, davidvincze commented
> Would not it be better to make this just part of the standard `DIRECT_XIP` instead of adding a new option?

Without enabling this additional mechanism, it is possible to boot an image without having to write/modify the flash.
Therefore for platform with relatively large write-sizes, the direct-xip mode can be a convenient alternative.

2020-10-30 08:39 UTC, nvlsianpu commented
``` consloe
** Booting Zephyr OS build zephyr-v2.4.0-1111-g8941f9a00c0b  ***
[00:00:00.398,529] <inf> mcuboot: Starting bootloader
[00:00:00.404,510] <inf> mcuboot: Primary slot: Image not found
[00:00:00.411,163] <inf> mcuboot: Secondary slot: version=1.1.0+0
[00:00:00.501,007] <inf> mcuboot: Booting image from the secondary slot
[00:00:00.508,361] <inf> mcuboot: Bootloader chainload address offset: 0x73000
[00:00:00.516,357] <inf> mcuboot: Jumping to the first image slot
*** Booting Zephyr OS build zephyr-v2.4.0-1111-g8941f9a00c0b  ***
*** Booting Zephyr OS build zephyr-v2.4.0-1111-g8941f9a00c0b  ***
[00:00:00.392,059] <inf> mcuboot: Starting bootloader
[00:00:00.398,040] <inf> mcuboot: Primary   slot: version=1.2.0+0
[00:00:00.404,876] <inf> mcuboot: Secondary slot: version=1.1.0+0
[00:00:00.493,438] <inf> mcuboot: Booting image from the primary slot
[00:00:00.500,610] <inf> mcuboot: Bootloader chainload address offset: 0xc000
[00:00:00.508,514] <inf> mcuboot: Jumping to the first image slot
*** Booting Zephyr OS build zephyr-v2.4.0-1111-g8941f9a00c0b  ***
Hello World! nrf52840dk_nrf52840
*** Booting Zephyr OS build zephyr-v2.4.0-1111-g8941f9a00c0b  ***
[00:00:00.256,347] <inf> mcuboot: Starting bootloader
[00:00:00.262,329] <inf> mcuboot: Primary   slot: version=1.2.0+0
[00:00:00.269,134] <inf> mcuboot: Secondary slot: version=1.1.0+0
[00:00:17.703,399] <err> mcuboot: Unable to find bootable image
*** Booting Zephyr OS build zephyr-v2.4.0-1111-g8941f9a00c0b  ***
[00:00:00.256,286] <inf> mcuboot: Starting bootloader
[00:00:00.262,268] <inf> mcuboot: Primary slot: Image not found
[00:00:00.268,890] <inf> mcuboot: Secondary slot: Image not found
[00:00:00.275,695] <err> mcuboot: Unable to find bootable image
```

2020-10-30 09:36 UTC, utzig commented
@nvlsianpu You might be missing `--pad` when creating images; it seems to check for `MAGIC` and delete if it's not there. A better strategy would be to validate and only erase when images are invalid.

2020-10-30 10:19 UTC, nvlsianpu approved these changes
Approved since it doesn't corrupted what is already working.
Any issues might been fixed after.

2020-10-30 14:44 UTC, nvlsianpu requested changes
Need to clarify why it doesn't work for me.

2020-10-30 15:59 UTC, davidvincze commented
> @nvlsianpu You might be missing `--pad` when creating images; it seems to check for `MAGIC` and delete if it's not there. A better strategy would be to validate and only erase when images are invalid.

In such a case I'm afraid  you could be left with a valid, but non-working firmware.

2020-10-30 16:02 UTC, davidvincze commented
@nvlsianpu it looks like after the third boot it found the image in the primary slot to be invalid.
[00:00:08.995,880] <err> mcuboot: Unable to find bootable image.

Or did the revert code delete the slot? Can you confirm that this image can be loaded? (without performing any upgrades)

2020-11-03 10:28 UTC, davidvincze commented
@nvlsianpu  I did perform a similar test and I was working as expected.
- image with higher version was booted from secondary slot,
- after reset it was deleted as it was not confirmed, booted image in primary slot,
- image image primary slot proved to be stable, it was made permanent (marked as confirmed by the imgtool) and 
  I could reset the board and boot this image (several times) and it was not erased by the bootloader

2020-11-03 16:59 UTC, nvlsianpu commented
Issue was that I was using imgtool from pip of version 1.6.0 which haven't this patch #806.

2020-11-03 16:59 UTC, nvlsianpu approved these changes

2020-11-03 18:58 UTC, utzig approved these changes

2020-11-03 20:52 UTC, merged