mgtool: Add support for setting fixed ROM address into image header
mcu-tools/mcuboot pull request #898
Opened 2020-12-14 13:18 UTC by de-nordic

The commit adds support for IMAGE_F_ROM_FIXED flag that allows setting
information on image base address into image_header.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2020-12-14 13:30 UTC, nvlsianpu approved these changes

2020-12-14 13:39 UTC, utzig commented on scripts/imgtool/image.py
>          'ENCRYPTED':             0x0000004,
Since you are changing this please put those in order.

2020-12-14 22:28 UTC, utzig requested changes
Please also update `Image.__repr__`

2020-12-14 22:28 UTC, utzig commented on scripts/imgtool/image.py
>          'ENCRYPTED':             0x0000004,
Since you are not adding the new value at the end, also sort this one into the correct position.

2020-12-14 22:28 UTC, utzig commented on scripts/imgtool/main.py
> +              help='Set flash address the image is build for.')
build for -> built for

2020-12-15 09:29 UTC, utzig approved these changes

2020-12-15 09:31 UTC, utzig commented
@de-nordic You might want to update https://github.com/mcu-tools/mcuboot/blob/master/scripts/imgtool/__init__.py#L15 to `1.8.0a1` in case you need a new release of `imgtool` to be published.

2020-12-15 21:32 UTC, d3zd3z approved these changes

2020-12-16 17:06 UTC, merged