Add support for ECDSA P256 using mbed TLS
mcu-tools/mcuboot pull request #918
Opened 2021-01-14 00:08 UTC by d3zd3z

Although tinycrypt is smaller and faster than mbed TLS at ECDSA, when some other functionality needs mbed TLS, bringing in tinycrypt as well would only serve to make the code larger. This patchset adds support for mbed TLS with ecdsa.

2021-01-14 00:09 UTC, d3zd3z commented
The abstraction ends up rather messy from all of this, and I'll probably end up redoing how it is done.

2021-01-15 21:04 UTC, d3zd3z commented
More in-depth discussion in #922.

2021-02-19 19:47 UTC, d3zd3z commented
I think this is a reasonable compromise solution. I do have a single define that affects the calling code as to whether it wants the key decoded or not. Before, I was decoding the key and then possibly not using the decoded key, which is less efficient.

2021-02-22 01:05 UTC, utzig requested changes
Implementation looks fine, would be nice to also have #884 for a complete Mbed TLS EC based implementation.

2021-02-22 01:05 UTC, utzig commented on boot/bootutil/src/image_ec256.c
> +	defined(MCUBOOT_USE_MBED_TLS)
tabs -> spaces

2021-02-22 01:05 UTC, utzig commented on boot/bootutil/include/bootutil/crypto/ecdsa_p256.h
> +					     uint8_t *sig, size_t sig_len)
tabs -> spaces

2021-02-22 01:05 UTC, utzig commented on boot/bootutil/include/bootutil/crypto/ecdsa_p256.h
> +					     uint8_t *sig, size_t sig_len)
tabs -> spaces

2021-02-22 17:50 UTC, d3zd3z commented on boot/zephyr/include/config-ecdsa.h
> +#define MBEDTLS_MPI_MAX_SIZE              256
Actually, these values don't really make any sense for ECDSA. 32 is fine here, and will save RAM.

2021-02-22 17:56 UTC, d3zd3z commented
@utzig: I've fixed the tabs, and replaced the MPI size with just 32, which is the value needed for P256.

2021-02-22 19:51 UTC, utzig approved these changes
LGTM

2021-02-23 08:39 UTC, nvlsianpu approved these changes

2021-02-23 09:06 UTC, nvlsianpu commented
Do  anyone know why `Travis CI - Branch` workflow was triggered?

2021-02-23 09:24 UTC, utzig commented
> Do anyone know why `Travis CI - Branch` workflow was triggered?

A branch was created on this fork and subsequently deleted.

2021-02-23 17:28 UTC, d3zd3z commented
> > Do anyone know why `Travis CI - Branch` workflow was triggered?
> 
> A branch was created on this fork and subsequently deleted.

Yeah, my bad. I accidentally pushed to the main project instead of my own repo. I deleted it shortly thereafter, but it was there long enough to anger Travis.

2021-02-23 17:29 UTC, merged