boot: zephyr: Switch to chosen zephyr,uart-mcumg for serial recovery
mcu-tools/mcuboot pull request #951
Opened 2021-02-26 14:13 UTC by de-nordic

The commit changes the default device selection, for serial recovery,
from the DTS chosen zephyr,uart-console to zephyr,uart-mcumgr.
This is more in line with Zephyr which uses the later for mcumgr
UART, which is also used for serial recovery in mcuboot.

The default configurations of Zephyr boards select the same device,
uart0, for both chosen devices; projects that do not use overlays to
change these selections will not be affected.

Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>

2021-02-26 14:38 UTC, de-nordic commented
@nvlsianpu When you have a moment.

2021-02-26 17:16 UTC, d3zd3z approved these changes

2021-03-01 10:33 UTC, nvlsianpu requested changes
Change of configuration source to zephyr,uart-mcumgr looks fine to me and it is reasonable.

Although this not solve issue which will be encountered if console will be enabled on same serial device. Compilation error should be still generated if configuration collides.

2021-03-03 07:45 UTC, de-nordic commented
> 
> 
> Change of configuration source to zephyr,uart-mcumgr looks fine to me and it is reasonable.
> 
> Although this not solve issue which will be encountered if console will be enabled on same serial device. Compilation error should be still generated if configuration collides.

I will try to figure this out, but the problem is that currently the UART device identifier is taken, from Kconfig option, as a string, which means that I cannot compare this at compile time. Additionally I am not able to use any of the DTS stuff as the Kconfig option, although comes from the DTS, can be modified by user.

2021-09-22 08:42 UTC, de-nordic commented
Replaced with https://github.com/mcu-tools/mcuboot/pull/1155

2021-09-22 08:42 UTC, closed without merging