Mbed: Make scratch BlockDevice customizable
mcu-tools/mcuboot pull request #984
Opened 2021-04-27 09:21 UTC by boraozgen

This change makes it possible to provide a custom scratch region BlockDevice, such as an external flash.

@AGlass0fMilk

2021-04-30 10:18 UTC, boraozgen commented
I actually wanted to ask if external scratch could cause any issues, as I never stumbled upon such an example. Thanks for the remark about encrypted images. Maybe this could be documented somewhere as a limitation.

2021-05-03 11:06 UTC, AGlass0fMilk commented
> Thanks for the remark about encrypted images. Maybe this could be documented somewhere as a limitation.

The best thing to do would be to make it a mutually-exclusive configuration option. This prevents developers from unknowingly enabling a potential security loophole. Unfortunately you can't rely on a developer reading a documentation footnote for something like this :sweat_smile: 

Perhaps we could introduce a new configuration option in the `mbed_lib.json` that allows you to retarget the scratch block device by overriding a function, similar to how the update/secondary block device is provided to Mcuboot now. Enabling this new option _and_ encrypted firmware updates at the same time can cause a compile-time error.

2021-05-03 11:10 UTC, boraozgen commented
I believe this should be documented in mcuboot core level, since this is not a port related consideration.

2021-05-08 02:05 UTC, AGlass0fMilk commented
> I believe this should be documented in mcuboot core level, since this is not a port specific consideration.
> 
> > Unfortunately you can't rely on a developer reading a documentation footnote for something like this
> 
> They better read the documentation if they are implementing an advanced security feature like this :)

While I agree with both points, I still think the compiler should be made to warn users at least. The hope is that mcuboot will become easier to use in Mbed-OS as integration is refined. Ease-of-use means more developers will just assume things work...

Maybe I'm a bit cynical but I think we should add a compile-time warning/error if the scratch BlockDevice overwrite option is enabled and encrypted images is enabled at the same time.

Do you have any thoughts on this @LDong-Arm?

2021-05-12 14:25 UTC, AGlass0fMilk commented
> @AGlass0fMilk How would you implement this check? Currently it is not a configuration option, and I don't know of a way to determine if the weak function has been overridden or not. Adding a configuration option just for warning purposes seems unnecessary to me.

I see your point. More configuration (especially just for warnings) will surely lead to configuration hell.

How about this: Add a disclaimer to the docstring comment of the weak `get_scratch_bd` function that says putting the scratch region on an external memory may cause security loopholes. Maybe include the information that @d3zd3z posted above.

Docstring comments are much likelier to be read/glanced at than documentation...

2021-05-12 14:26 UTC, AGlass0fMilk requested changes

2021-05-12 14:26 UTC, AGlass0fMilk commented on boot/mbed/src/secondary_bd.cpp
> + * This is a weak symbol so the user can override it.
Add security warning here about putting scratch region on external flash.

2021-05-13 10:49 UTC, boraozgen commented on boot/mbed/src/secondary_bd.cpp
> + * This is a weak symbol so the user can override it.
Done

2021-05-13 12:51 UTC, AGlass0fMilk commented
Nit: can you combine the docstring comments and just put all the info above the declaration in the header? Typically I just put docstrings in the header.

Sorry for the small changes 😅

2021-05-14 10:42 UTC, boraozgen commented
You're right, how about this?

2022-03-07 01:46 UTC, closed without merging